[package]
name = "benchpress_sys"
version = "0.1.0"
authors = ["Peter Jaszkowiak <p.jaszkow@gmail.com>"]

[dependencies]
itertools = "0.7.8"
regex = "1.0.2"
lazy_static = "1.0.2"
json = "0.11.13"

[profile.release]
debug = true