[package]
name = "benchpress_sys"
version = "0.1.0"
authors = ["Peter Jaszkowiak <p.jaszkow@gmail.com>"]

[dependencies]
itertools = "0.8"
regex = "1.3"
lazy_static = "1.4"
json = "0.12"

[profile.release]
debug = true